services:
  crabdis:
    image: pxseu/crabdis:latest
    restart: always
    container_name: crabdis
    ports:
      - "6379:6379/tcp"
    volumes:
      - crabdis_data:/data
    command: ["--dir", "/data", "--save", "60 1"]

volumes:
  crabdis_data:
